// Warning!: This file is generated automatically using ucd2cs.py script.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace IronText.Algorithm
{
    /// <summary>
    /// Don't edit this file! It was generated by the 'ucd2cs.py'.
    /// You can find script in the same directory.
    /// </summary>
    public partial class UnicodeIntSetType
    {
        public IntSet GetUnicodeCategory(string name)
        {
            switch (name)
            {
                case "Ps": return OpenPunctuation;
                case "Nl": return LetterNumber;
                case "No": return OtherNumber;
                case "Lo": return OtherLetter;
                case "Ll": return LowercaseLetter;
                case "Lm": return ModifierLetter;
                case "Nd": return DecimalDigitNumber;
                case "Pc": return ConnectorPunctuation;
                case "Lt": return TitlecaseLetter;
                case "Lu": return UppercaseLetter;
                case "Pf": return FinalQuotePunctuation;
                case "Pd": return DashPunctuation;
                case "Pe": return ClosePunctuation;
                case "Pi": return InitialQuotePunctuation;
                case "Po": return OtherPunctuation;
                case "Me": return EnclosingMark;
                case "Mc": return SpacingCombiningMark;
                case "Mn": return NonSpacingMark;
                case "Sk": return ModifierSymbol;
                case "So": return OtherSymbol;
                case "Sm": return MathSymbol;
                case "Sc": return CurrencySymbol;
                case "Zl": return LineSeparator;
                case "Co": return PrivateUse;
                case "Cn": return Unassigned;
                case "Cc": return Control;
                case "Cf": return Format;
                case "Cs": return Surrogate;
                case "Zp": return ParagraphSeparator;
                case "Zs": return SpaceSeparator;
                default: return null;
            }
        }
    }
}
